set(VIBE_CORE_SOURCES
  src/session/launch_spec.cpp
  src/session/posix_pty_process.cpp
  src/session/provider_config.cpp
  src/session/session_record.cpp
  src/session/session_runtime.cpp
  src/session/session_types.cpp
  src/session/session_lifecycle.cpp
)

set(VIBE_TEST_SOURCES
  tests/session/launch_spec_test.cpp
  tests/session/posix_pty_process_test.cpp
  tests/session/provider_config_test.cpp
  tests/session/session_record_test.cpp
  tests/session/session_runtime_test.cpp
  tests/session/session_snapshot_test.cpp
  tests/session/session_types_test.cpp
  tests/session/session_lifecycle_test.cpp
)
