set(VIBE_CORE_SOURCES
  src/cli/daemon_client.cpp
  src/net/json.cpp
  src/net/request_parsing.cpp
  src/net/http_server.cpp
  src/net/http_shared.cpp
  src/net/websocket_shared.cpp
  src/store/file_stores.cpp
  src/service/git_inspector.cpp
  src/service/session_manager.cpp
  src/session/launch_spec.cpp
  src/session/posix_pty_process.cpp
  src/session/provider_config.cpp
  src/session/session_output_buffer.cpp
  src/session/session_record.cpp
  src/session/session_runtime.cpp
  src/session/session_types.cpp
  src/session/session_lifecycle.cpp
)

set(VIBE_TEST_SOURCES
  tests/auth_store/interface_contract_test.cpp
  tests/cli/daemon_client_test.cpp
  tests/net/http_json_test.cpp
  tests/net/http_server_integration_test.cpp
  tests/net/request_parsing_test.cpp
  tests/net/http_shared_test.cpp
  tests/net/websocket_shared_test.cpp
  tests/store/file_stores_test.cpp
  tests/service/git_inspector_test.cpp
  tests/session/launch_spec_test.cpp
  tests/session/posix_pty_process_test.cpp
  tests/session/provider_config_test.cpp
  tests/session/session_output_buffer_test.cpp
  tests/session/session_record_test.cpp
  tests/session/session_runtime_test.cpp
  tests/session/session_snapshot_test.cpp
  tests/session/session_types_test.cpp
  tests/session/session_lifecycle_test.cpp
)
